# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/main.exe ."   # 构建命令，输出到 /bin 目录下
bin = "./bin/main.exe"             # 执行文件的路径
include_ext = ["go"]               # 只监听 Go 文件
exclude_dir = ["web", "tmp", "vendor", "assets", ".git", ".idea", "bin", "docs", "log"]  # 不监听的目录

[log]
time = false
