definitions:
  handler.LoginResponse:
    properties:
      code:
        type: integer
      msg:
        type: string
      token:
        type: string
      uid:
        type: integer
    type: object
info:
  contact: {}
paths:
  /login:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Perform user login with username and password.
      parameters:
      - description: User name
        in: formData
        name: user
        required: true
        type: string
      - description: Password
        in: formData
        name: pass
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful login, token returned
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "400":
          description: Invalid request, user name or password format error
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "403":
          description: Unauthorized, wrong user name or password
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "500":
          description: Internal server error, token generation failed
          schema:
            $ref: '#/definitions/handler.LoginResponse'
      summary: User login
      tags:
      - authentication
swagger: "2.0"
